### ISSUE TITLE
New name for the library

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/layer-manager#75]
If you make google search “layer-manager” you get all sort of things. I think that with v3 we need to start thinking of a better name.

Proposals:
- Butler
- Cousteau
- Milú (Tintin’s dog)
- Thornberry
- Mafalda

I think we could use this issue to add more proposals and discuss it further...

**Comment by davidsingal** [comment]
I love you open this issue in order to make conversations using this channel 👍 

About the name of the library, I agree with another name could be more accurate with the purpose of the library. But, for now, I don't have the feeling it is needed at this moment.

I get this repository easily searching in Google by the terms `layer manager library`. Is it enough for now? What do you think?

**Comment by sorodrigo** [comment]
I think that `v3` being a major release is a perfect opportunity to make the library more fun/sexy. That said, I’d like this issue is to be a place to come up with other proposals, not to come up with reasons why is not priority - no offense.

I don’t mean to find a more descriptive name, I don’t think that’s necessarily a requirement. I think a shorter name, easier to brand, unique, with references to something else (I took as an example explorers from pop culture), that would be great.

**Comment by davidsingal** [comment]
I was thinking on it a bit more and I think the name is not so important. I'm open to change it if people support that decision.

More important is to be sure people can find this library properly. I mean, we can add more tags in the repository and be clear in the description of this library. So, I'm going to read about how to improve the visibility of an repository.

**Comment by sorodrigo** [comment]
All that is good, a problem will face is people don’t trust libraries without stars. I’d say the first step is improving documentation (before improving visibility or SEO), then doing some evangelism - going to conferences, writing blog post, etc - and for that, the name is paramount. If you want to discuss further visibility or docs maybe better to use another issue?

**Comment by davidsingal** [comment]
Another issue works for me.

**Comment by edbrett** [comment]
So I'm not sure of the importance of addressing this before other areas (docs etc), but I do agree it important we have branding that we are all happy with moving forwards. It would be nice to have that done with v3, but it isn't essential for me. It depends you you timeline for speaking about the lib.

As for the names themselves, I like the ones that are painfully obvious, for example `Layer Manager` as that is what it does. I always remember and can google them again after I have found them because I can search `js lib map layer manager` and there you have libraries that do that. Agreed, that can also happen from a well written description and other things. I am no expert on this for sure. Im pretty certain we need to put emojis and have `blazin` written some where otherwise we've missed the mark royally. 

Anything that is hard to say in English I would say isn't a great idea. For example (and maybe this is because I am uncultured swine) but I had no idea Cousteau was how his name was written, so I had no idea what that meant. Do you have any good examples of libs that have eddy names that work well?

**Comment by sorodrigo** [comment]
I guess React and Angular and Pollyjs and Ember and React Final Form and LinguiJS? Did you know that react is not reactive?
Anyway, feel free to reopen.

**Comment by mbarrenechea** [comment]
millefeuille
